version: '3'

services:

  cutsolver:
    build: .
    image: modischfabrications/cutsolver:latest
    restart: unless-stopped
    ports:
      - "8000:80"
    environment:
      - BRUTEFORCE_MAX_COMBINATIONS=4000
      - SOLVER_N_MAX=1500

  cutsolver_frontend:
    image: modischfabrications/cutsolver_frontend:latest
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - cutsolver
    environment:
      # point this to your backend host URL
      - VUE_APP_BACKEND_SOLVER_URL=http://localhost:8000/solve
